#!/bin/bash
#
# Install Zoneminder
# zoneminder
#
# OS: Ubuntu 16.04.3 LTS
# Author: Jeffrey Jensen
# Email: jensenj08@gmail.com
#
# Description:
# Install zoneminder with all the pesky bits
#
##############################################

# https://zoneminder.readthedocs.io/en/stable/installationguide/ubuntu.html

systemctl restart mysql
apt-get install zoneminder
mysql -uroot -p < /usr/share/zoneminder/db/zm_create.sql
mysql -uroot -p -e "grant select,insert,update,delete,create,alter,index,lock tables on zm.* to 'zmuser'@localhost identified by 'zmpass';"
chmod 740 /etc/zm/zm.conf
chown root:www-data /etc/zm/zm.conf
chown -R www-data:www-data /usr/share/zoneminder/
a2enconf zoneminder
a2enmod cgi
a2enmod rewrite
systemctl enable zoneminder
systemctl start zoneminder

# Ghetto rig these permissions.
chod 777 /dev/video0

echo "Now you need to edit the php.ini timezone."
echo "nano /etc/php/7.0/apache2/php.ini"
echo "[Date]"
echo "; Defines the default timezone used by the date functions"
echo "; http://php.net/date.timezone"
echo "date.timezone = America/New_York"
echo "systemctl reload apache2"
echo ""
