#!/bin/bash
#
# Install Git
# git
#
# OS: Ubuntu 16.04.3 LTS
# Author: Jeffrey Jensen
# Email: jensenj08@gmail.com
# 
# Description: 
# Install git and setup the basic
# user information 
########################################

# Force users to run installations as root.
if [[ $EUID -ne 0 ]]; then
   echo "ERROR: You must run this installation process as root!" 
   exit 1
fi

if [ -z "$1" || -z "$2" ]; then
    echo "Please provide arguments in the format: "
    echo "install-git <full-name> <email-address>"
    exit 1
fi

# Configuration Values for:
# --global user.email
# --global user.name
# We want to get these values before 
# running the installation, so that the user
# can ignore the script until it's finished. 
NAME=$1
EMAIL=$2




# Install git
apt-get update
apt-get install git

# Set user preferences.
git config --global user.email $EMAIL
git config --global user.name $NAME