#!/bin/bash
#
# Install Git
# git
#
# OS: Ubuntu 16.04.3 LTS
# Author: Jeffrey Jensen
# Email: jensenj08@gmail.com
# 
# Description: 
# Install git and setup the basic
# user information 
########################################

# Configuration Values for:
# --global user.email
# --global user.name
# We want to get these values before 
# running the installation, so that the user
# can ignore the script until it's finished. 
echo "Select an email to be associated with your git commits."
echo "git config --global user.email <your@email.address>:"
read EMAIL

echo "Select a name to be associated with your git commits."
echo "git config --global user.name <your name>:"
read NAME

# Install git
apt-get update
apt-get install git

# Set user preferences.
git config --global user.email $EMAIL
git config --global user.name $NAME

# Allow users to push to any
# branch on this server. 
git config --global receive.denyCurrentBranch ignore