#!/bin/bash
#
# Install Git
# git
#
# OS: Ubuntu 16.04.3 LTS
# Author: Jeffrey Jensen
# Email: jensenj08@gmail.com
# 
# Description: 
# Install git and setup the basic
# user information 
########################################

# Configuration Values for:
# --global user.email
# --global user.name
# We want to get these values before 
# running the installation, so that the user
# can ignore the script until it's finished. 
echo "Select an email to be associated with your git commits."
echo "git config --global user.email <your@email.address>:"
EMAIL="jensenj08@gmail.com"

echo "Select a name to be associated with your git commits."
echo "git config --global user.name <your name>:"
NAME="Jeffrey Jensen"

# Install git
sudo apt-get update
sudo apt-get install git

# Set user preferences.
sudo git config --global user.email $EMAIL
sudo git config --global user.name $NAME