#!/bin/bash
#
# Install PiHole
# pi-hole
#
# OS: Ubuntu 16.04.3 LTS
# Author: Jeffrey Jensen
# Email: jensenj08@gmail.com
#
# Description:
# PiHole is a dns server designed to block
# ads.
#
##############################################

# Install PiHole in one command.
curl -sSL https://install.pi-hole.net | bash
