#!/bin/bash
#
# Configure Fail2Ban ssh
# fail2ban
#  
# OS: Ubuntu 16.04.3 LTS
# Author: Jeffrey Jensen
# Email: jensenj08@gmail.com
#
# Description:
# Configure fail2ban ssh settings.
# 
##############################################