#!/bin/bash
#
# Install Fail2Ban
# fail2ban
#  
# OS: Ubuntu 16.04.3 LTS
# Author: Jeffrey Jensen
# Email: jensenj08@gmail.com
#
# Description:
# Install fail2ban and configure the service.
# this script has NOT been tested.
# 
##############################################

# Force users to run installations as root.
if [[ $EUID -ne 0 ]]; then
   echo "ERROR: You must run this installation process as root!" 
   exit 1
fi

# Install fail2ban
apt-get install fail2ban