#!/bin/bash
#
# Install Pritunl
# pritunl
#
# OS: Ubuntu 16.04.3 LTS
# Author: Jeffrey Jensen
# Email: jensenj08@gmail.com
# 
# Description: 
# Install pritunl and mongodb which is
# a dependency.
# 
########################################

# Add the repository for mongodb, and it's key.
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
add-apt-repository 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse'

# Add the pritunl repo as well as well as it's key.
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7568D9BB55FF9E5287D586017AE645C0CF8E292A
add-apt-repository 'deb http://repo.pritunl.com/stable/apt xenial main'

# Now that we added repos, pull newly available repos. 
apt-get -y update

# Install pritunl and mongodb.
apt-get -y install pritunl mongodb-org python-pip

# Start mongodb. 
systemctl start mongod

# Start pritunl.
systemctl start pritunl

# Display the status for mongodb.
systemctl status mongod

# Display the status for pritunl.
systemctl status pritunl

# Make sure the services begin on startup.
systemctl enable pritunl mongod

# Open file imits
sudo sh -c 'echo "* hard nofile 64000" >> /etc/security/limits.conf'
sudo sh -c 'echo "* soft nofile 64000" >> /etc/security/limits.conf'
sudo sh -c 'echo "root hard nofile 64000" >> /etc/security/limits.conf'
sudo sh -c 'echo "root soft nofile 64000" >> /etc/security/limits.conf'

echo "---------------------------------------"
ifconfig
echo "---------------------------------------"
echo "INSTRUCTIONS::"
echo "---------------------------------------"
echo "Copy this key: "
pritunl setup-key
echo "---------------------------------------"
echo "You should be able to get to the gui manager"
echo "at http://<your-ip>/ and then paste your key in."
echo "---------------------------------------"
echo "Sign in:"
echo "User: pritunl"
echo "Pass: pritunl"
echo "---------------------------------------"
echo "Username: <your-new-username>"
echo "Public Address: <your-domain-name>"
echo "Web Console port: 443"
echo "Password: <something-secure>"
echo "Lets Encrypt Domain: <just-leave-this-blank>"
echo "---------------------------------------"
echo "Now you can add an organization and users."
echo "Add a server."
echo "Name: <whatever>"
echo "Port: <something-crazy>"
echo "Protocol: UDP"
echo "DNS: <your-dns>|<some-public-dns>"
echo "---------------------------------------"
echo "Attach your organization to the vpn."
echo "Remove 0.0.0.0/0 route. (OPTIONAL)"
echo "Add Route: <your-local-network-address>"
echo "Start Server"
echo "Have fun!"